import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";

/**
 * Flat config. Deliberately narrow: this is a hook-heavy React app, so the
 * rules that earn their keep are the hook rules (a missing dependency here
 * shows up as a stale timer or a range that stops refreshing, not as a type
 * error) plus the unused/floating-value checks TypeScript doesn't cover.
 * Stylistic rules are left out — the codebase is consistent already and
 * churning it would bury real history.
 */
export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "coverage/**",
      // Generated by the Power Platform SDK — not ours to lint.
      "src/generated/**",
      ".power/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser, ...globals.es2021 },
    },
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // An unused argument is often deliberate (event handlers, callback
      // signatures); an underscore prefix says so.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
      // Vite bundles for a browser, and console.error/warn are how the
      // service layer reports partial loads; console.log is not.
      "no-console": ["warn", { allow: ["error", "warn"] }],
    },
  },
  {
    files: ["**/*.test.{ts,tsx}"],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
    rules: {
      // Tests reach into internals and stub host APIs; the casts that needs
      // are noise to flag one by one.
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  {
    files: ["*.config.{js,ts}"],
    languageOptions: { globals: globals.node },
  },
);
