import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "jsdom",
    // Off by default, and with it off a `styles.css?raw` import resolves to an
    // empty string rather than the stylesheet — which is what the contrast
    // assertions in styles.contrast.test.ts read. Nothing under src/components
    // imports CSS (only main.tsx does, and it isn't tested), so turning this on
    // costs the rest of the suite nothing.
    css: true,
    include: ["src/**/*.test.ts", "src/**/*.test.tsx"],
    // CI machines run in UTC, where every day is exactly 24 hours and the
    // clock never moves — so the whole class of DST bugs (#87) is invisible
    // there. Pin the suite to a zone that observes it; individual tests that
    // want a different zone still stub TZ themselves.
    env: { TZ: "America/New_York" },
    coverage: {
      provider: "v8",
      // text for the CI log, html to browse locally, lcov for any tooling
      // that wants to ingest it.
      reporter: ["text", "html", "lcov"],
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.test.{ts,tsx}",
        // Generated by the Power Platform SDK, plus type-only and entry
        // modules with nothing to execute.
        "src/generated/**",
        "src/types/**",
        "src/main.tsx",
        "src/vite-env.d.ts",
      ],
    },
  },
});
