/**
 * dataverseService.ts
 *
 * Talks to Microsoft Dataverse via the @microsoft/power-apps SDK using the
 * code generated by `pac code add-data-source` into src/generated/. When the
 * app runs outside the Power Apps host (Vite dev), it falls back to a
 * localStorage-backed mock with identical semantics.
 *
 * Dataverse tables (must exist in the env before deploying; logical names
 * use the singular, entity-set names use the plural -ses form):
 *   ever_projects    / ever_projectses    — Project records
 *   ever_workitems   / ever_workitemses   — Work Item records
 *   ever_timeentries / ever_timeentrieses — Time Entry records
 *
 * Lookup columns are `ever_project` and `ever_workitem` (NOT *_id). On reads
 * they surface as `_ever_project_value` / `_ever_workitem_value`; writes use
 * `ever_project@odata.bind` / `ever_workitem@odata.bind` with the entity-SET
 * path (plural form), e.g. `/ever_projectses(<guid>)`.
 *
 * Time entries are user-scoped: reads filter by ever_userid eq <current user>,
 * writes stamp the current user. Make sure initCurrentUser() has resolved
 * before calling any of these.
 */
import type { Project, Task, TimeEntry } from "../types";
import { getCurrentUser, isPowerAppsHost, getDataverseOrgUrl } from "./userService";
import { MicrosoftDataverseService } from "../generated";

// ---------------------------------------------------------------------------
// Entity logical names (FetchXML, $filter on lookups) vs entity SET names
// (Web API paths and @odata.bind). The Dataverse pluralization rule appends
// "es" to names already ending in "s", so all three of ours look like ...ses.
// ---------------------------------------------------------------------------
const SETS = {
  projects: "ever_projectses",
  tasks: "ever_workitemses",
  entries: "ever_timeentrieses",
} as const;

const ACCEPT = "application/json";
const PREFER_RETURN = "return=representation";
// Org URL, required by every *WithOrganization SDK call (the connector rejects
// the no-org "current environment" variants with HTTP 400). Resolved at RUNTIME
// from the connection via getDataverseOrgUrl() — see userService — so a single
// promoted build targets dev in dev, QA in QA, and prod in prod automatically.
// (Baking it in at build time broke one-artifact promotion: a promoted build
// kept calling whichever environment it was compiled against.)
function orgUrl(): string {
  return getDataverseOrgUrl();
}

// ---------------------------------------------------------------------------
// Retry helper — wraps write operations with exponential backoff for transient
// Dataverse errors (429 rate limit, 503 service unavailable).
// ---------------------------------------------------------------------------
async function retryWithBackoff<T>(fn: () => Promise<T>, maxAttempts = 3): Promise<T> {
  let delay = 1000;
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      return await fn();
    } catch (err: unknown) {
      const isTransient = (() => {
        if (!err || typeof err !== "object") return false;
        const e = err as Record<string, unknown>;
        const status = typeof e.status === "number" ? e.status
          : typeof e.statusCode === "number" ? e.statusCode
          : 0;
        if (status === 429 || status === 503) return true;
        // Some SDK errors carry the status in the message string.
        const msg = typeof e.message === "string" ? e.message : "";
        return msg.includes("429") || msg.includes("503");
      })();

      if (!isTransient || attempt === maxAttempts) throw err;

      // Respect Retry-After header when available (SDK may surface it as retryAfter).
      const retryAfterSec = (() => {
        const e = err as Record<string, unknown>;
        const v = e.retryAfter ?? e["retry-after"];
        const n = Number(v);
        return Number.isFinite(n) && n > 0 ? n * 1000 : null;
      })();

      await new Promise((res) => setTimeout(res, retryAfterSec ?? delay));
      delay *= 2;
    }
  }
  throw new Error("retryWithBackoff: unreachable");
}

// ---------------------------------------------------------------------------
// SDK result helpers — every call returns { success, data, error? }; unwrap
// or throw so the calling hooks can keep using try/catch.
// ---------------------------------------------------------------------------
function unwrap<T>(result: { success: boolean; data: T; error?: unknown }, op: string): T {
  if (!result.success) {
    const err = result.error;
    if (err instanceof Error) throw err;
    throw new Error(`${op} failed: ${typeof err === "string" ? err : JSON.stringify(err ?? {})}`);
  }
  return result.data;
}

// The ListRecords response is an OData v9 envelope with a `value` array.
// Each item is wrapped by the SDK as `{ dynamicProperties: { ...row } }`.
// FetchXML-based queries page differently from $filter ones (see below), so
// the envelope can also carry a paging-cookie annotation instead of nextLink.
interface DynItem { dynamicProperties?: Raw }
interface ListEnvelope {
  value?: DynItem[];
  "@odata.nextLink"?: string;
  "@Microsoft.Dynamics.CRM.fetchxmlpagingcookie"?: string;
}

// Dataverse caps list responses (default 5,000 rows) and signals more data via
// @odata.nextLink. Pull the $skiptoken out of that link so we can keep paging
// through the SDK, which accepts $skiptoken but not a raw nextLink URL.
function extractSkipToken(nextLink?: string): string | undefined {
  if (!nextLink) return undefined;
  try {
    return new URL(nextLink).searchParams.get("$skiptoken") ?? undefined;
  } catch {
    return undefined;
  }
}

// FetchXML-based Web API queries don't page via @odata.nextLink/$skiptoken —
// Dataverse instead returns a paging-cookie annotation, which must be
// echoed back (HTML-escaped) as a `paging-cookie` attribute on <fetch>,
// alongside an incremented `page` attribute, to get the next page.
function withFetchPaging(fetchXml: string, page: number, pagingCookie?: string): string {
  if (page <= 1 && !pagingCookie) return fetchXml;
  const cookieAttr = pagingCookie ? ` paging-cookie="${escapeXmlAttr(pagingCookie)}"` : "";
  return fetchXml.replace(/<fetch(\s|>)/, `<fetch page="${page}"${cookieAttr}$1`);
}

// Hard ceiling so a misbehaving nextLink/paging-cookie can never loop forever.
const MAX_PAGES = 20;

// Module-level warning sink. Wire up via setPaginationWarningHandler() so the
// service can surface non-fatal partial-load warnings to the UI without
// importing React or hooks.
type WarningHandler = (message: string) => void;
let paginationWarningHandler: WarningHandler | null = null;
export function setPaginationWarningHandler(fn: WarningHandler | null): void {
  paginationWarningHandler = fn;
}

async function listAllPages(
  entitySet: string,
  filter: string | undefined,
  orderby: string | undefined,
  fetchXml?: string,
): Promise<Raw[]> {
  const rows: Raw[] = [];
  let skiptoken: string | undefined;
  let pagingCookie: string | undefined;
  for (let page = 0; page < MAX_PAGES; page++) {
    let env: ListEnvelope;
    try {
      const result = await MicrosoftDataverseService.ListRecordsWithOrganization(
        orgUrl(),
        entitySet,
        undefined, // prefer
        ACCEPT,
        undefined, // x-ms-odata-metadata-full
        undefined, // MSCRM.IncludeMipSensitivityLabel
        undefined, // $select
        fetchXml ? undefined : filter,
        fetchXml ? undefined : orderby,
        undefined, // $expand
        fetchXml ? withFetchPaging(fetchXml, page + 1, pagingCookie) : undefined,
        undefined, // $top
        fetchXml ? undefined : skiptoken,
      );
      env = unwrap(result, `List ${entitySet}`) as unknown as ListEnvelope;
    } catch (err) {
      if (page === 0) {
        // First page failure is fatal — there's nothing useful to return.
        throw err;
      }
      // Mid-pagination error: return what we have and warn the user.
      console.error(`Pagination error on page ${page} of ${entitySet}:`, err);
      paginationWarningHandler?.(
        "Some entries may not be shown — try narrowing your date range"
      );
      return rows;
    }
    for (const item of env?.value ?? []) rows.push(unwrapRow(item));
    if (fetchXml) {
      pagingCookie = env?.["@Microsoft.Dynamics.CRM.fetchxmlpagingcookie"];
      if (!pagingCookie) { skiptoken = undefined; break; }
      skiptoken = "more"; // sentinel so the exceeded-MAX_PAGES check below still fires
    } else {
      skiptoken = extractSkipToken(env?.["@odata.nextLink"]);
      if (!skiptoken) break;
    }
  }
  if (skiptoken) {
    // Exceeded MAX_PAGES — return partial data with a warning rather than
    // throwing, so the user sees what was loaded instead of a blank page.
    console.error(`Loading ${entitySet} exceeded ${MAX_PAGES} pages; partial data returned.`);
    paginationWarningHandler?.(
      "Some entries may not be shown — try narrowing your date range"
    );
  }
  return rows;
}

// The SDK wraps Dataverse rows (both list items and create/update responses)
// in a `dynamicProperties` object. Peel that off so the mappers see the row.
function unwrapRow(x: unknown): Raw {
  if (!x || typeof x !== "object") return {};
  const obj = x as Raw;
  const dyn = obj.dynamicProperties;
  if (dyn && typeof dyn === "object") return dyn as Raw;
  return obj;
}

// Returns true if val looks like a meaningful field value (not "" / null / undefined).
function isFilled(val: unknown): boolean {
  if (val === undefined || val === null) return false;
  if (typeof val === "string") return val.length > 0;
  return true;
}

// Overlay mapped onto input: keep mapped fields where present, otherwise fall
// back to whatever we sent. Covers the case where the Dataverse connector
// silently drops the response body despite prefer=return=representation, which
// would otherwise replace the user's optimistic record with empty fields.
export function mergeOver<T extends object>(input: T, mapped: T): T {
  const out: Record<string, unknown> = { ...(input as Record<string, unknown>) };
  for (const [k, v] of Object.entries(mapped as Record<string, unknown>)) {
    if (isFilled(v)) out[k] = v;
  }
  return out as T;
}

// ---------------------------------------------------------------------------
// Dataverse <-> model mapping
// ---------------------------------------------------------------------------
type Raw = Record<string, unknown>;

function str(r: Raw, key: string): string | undefined {
  const v = r[key];
  return typeof v === "string" ? v : undefined;
}

function num(r: Raw, key: string): number | undefined {
  const v = r[key];
  return typeof v === "number" && Number.isFinite(v) ? v : undefined;
}

function mapProject(r: Raw): Project {
  return {
    id: (str(r, "ever_projectsid") ?? str(r, "id")) as string,
    name: str(r, "ever_name") ?? "",
    color: str(r, "ever_color") ?? "#6366f1",
    description: str(r, "ever_description"),
    ratio: num(r, "ever_ratio"),
    jiraTicket: str(r, "ever_jiraticket"),
    isActive: num(r, "statecode") === 0,
    createdAt: str(r, "createdon") ?? new Date().toISOString(),
  };
}

function mapTask(r: Raw): Task {
  return {
    id: (str(r, "ever_workitemsid") ?? str(r, "id")) as string,
    projectId: str(r, "_ever_project_value") ?? "",
    name: str(r, "ever_name") ?? "",
    description: str(r, "ever_description"),
    isActive: num(r, "statecode") === 0,
  };
}

export function mapEntry(r: Raw): TimeEntry {
  // Dataverse can return ever_date either as "YYYY-MM-DD" or as a full ISO
  // timestamp ("YYYY-MM-DDT00:00:00Z") depending on the column's behavior.
  // The rest of the app keys calendar/timesheet rows off "YYYY-MM-DD", so
  // anything past the "T" must be stripped.
  const rawDate = str(r, "ever_date") ?? "";
  return {
    id: (str(r, "ever_timeentriesid") ?? str(r, "id")) as string,
    projectId: str(r, "_ever_project_value") ?? "",
    taskId: str(r, "_ever_workitem_value"),
    description: str(r, "ever_description"),
    startTime: str(r, "ever_starttime") ?? "",
    endTime: str(r, "ever_endtime"),
    durationMinutes: num(r, "ever_durationminutes"),
    ratio: num(r, "ever_ratio"),
    jiraTicket: str(r, "ever_jiraticket"),
    date: rawDate.split("T")[0],
    userId: str(r, "ever_userid") ?? "",
    userDisplayName:
      str((r.owninguser as Raw) ?? {}, "fullname") ??
      str((r.ownerid as Raw) ?? {}, "fullname") ??
      str(r, "ownerid_fullname") ??
      "",
  };
}

function projectToDataverse(p: Omit<Project, "id" | "createdAt"> | Partial<Project>): Raw {
  const out: Raw = {};
  if (p.name !== undefined) out.ever_name = p.name;
  if (p.color !== undefined) out.ever_color = p.color;
  if (p.description !== undefined) out.ever_description = p.description ?? null;
  if (p.ratio !== undefined) out.ever_ratio = p.ratio ?? null;
  if (p.jiraTicket !== undefined) out.ever_jiraticket = p.jiraTicket || null;
  return out;
}

function taskToDataverse(t: Omit<Task, "id"> | Partial<Task>): Raw {
  const out: Raw = {};
  if (t.name !== undefined) out.ever_name = t.name;
  if (t.description !== undefined) out.ever_description = t.description ?? null;
  if (t.projectId !== undefined) {
    out["ever_project@odata.bind"] = `/${SETS.projects}(${t.projectId})`;
  }
  return out;
}

export function entryToDataverse(e: Omit<TimeEntry, "id"> | Partial<TimeEntry>): Raw {
  const out: Raw = {};
  if (e.description !== undefined) out.ever_description = e.description ?? null;
  if (e.startTime !== undefined) out.ever_starttime = e.startTime;
  if (e.endTime !== undefined) out.ever_endtime = e.endTime ?? null;
  if (e.durationMinutes !== undefined) out.ever_durationminutes = e.durationMinutes ?? null;
  if (e.ratio !== undefined) out.ever_ratio = e.ratio ?? null;
  if (e.jiraTicket !== undefined) out.ever_jiraticket = e.jiraTicket || null;
  if (e.date !== undefined) out.ever_date = e.date;
  out.ever_userid = getCurrentUser().id;
  if (e.projectId !== undefined) {
    out["ever_project@odata.bind"] = `/${SETS.projects}(${e.projectId})`;
  }
  if ("taskId" in e) {
    out["ever_workitem@odata.bind"] = e.taskId ? `/${SETS.tasks}(${e.taskId})` : null;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Local mock store (Vite dev only)
// ---------------------------------------------------------------------------
const STORAGE_KEYS = {
  projects: "tt_projects",
  tasks: "tt_tasks",
  entries: "tt_entries",
} as const;

function load<T>(key: string): T[] {
  try {
    return JSON.parse(localStorage.getItem(key) || "[]") as T[];
  } catch {
    return [];
  }
}

function persist<T>(key: string, data: T[]): void {
  localStorage.setItem(key, JSON.stringify(data));
}

function uuid(): string {
  return crypto.randomUUID();
}

// ---------------------------------------------------------------------------
// Projects
// ---------------------------------------------------------------------------
export async function getProjects(): Promise<Project[]> {
  if (!isPowerAppsHost()) {
    return load<Project>(STORAGE_KEYS.projects)
      .filter((p) => p.isActive)
      .sort((a, b) => a.name.localeCompare(b.name));
  }
  const rows = await listAllPages(SETS.projects, "statecode eq 0", "ever_name asc");
  return rows.map(mapProject);
}

export async function createProject(data: Omit<Project, "id" | "createdAt">): Promise<Project> {
  if (!isPowerAppsHost()) {
    const project: Project = { ...data, id: uuid(), createdAt: new Date().toISOString() };
    const all = load<Project>(STORAGE_KEYS.projects);
    persist(STORAGE_KEYS.projects, [...all, project]);
    return project;
  }
  const result = await retryWithBackoff(() => MicrosoftDataverseService.CreateRecordWithOrganization(
    PREFER_RETURN,
    ACCEPT,
    orgUrl(),
    SETS.projects,
    projectToDataverse(data),
  ));
  const inputAsProject: Project = { ...data, id: "", createdAt: new Date().toISOString() };
  return mergeOver(inputAsProject, mapProject(unwrapRow(unwrap(result, "Create project"))));
}

export async function updateProject(id: string, data: Partial<Project>): Promise<Project> {
  if (!isPowerAppsHost()) {
    const all = load<Project>(STORAGE_KEYS.projects);
    const idx = all.findIndex((p) => p.id === id);
    if (idx === -1) throw new Error("Project not found");
    all[idx] = { ...all[idx], ...data };
    persist(STORAGE_KEYS.projects, all);
    return all[idx];
  }
  const result = await retryWithBackoff(() => MicrosoftDataverseService.UpdateRecordWithOrganization(
    PREFER_RETURN,
    ACCEPT,
    orgUrl(),
    SETS.projects,
    id,
    projectToDataverse(data),
  ));
  // Patch needs all fields populated for the UI to render correctly even when
  // the connector returns an empty body.
  const inputAsProject = { ...data, id } as Project;
  return mergeOver(inputAsProject, mapProject(unwrapRow(unwrap(result, "Update project"))));
}

// ---------------------------------------------------------------------------
// Tasks
// ---------------------------------------------------------------------------
export async function getTasksForProject(projectId: string): Promise<Task[]> {
  if (!isPowerAppsHost()) {
    return load<Task>(STORAGE_KEYS.tasks).filter((t) => t.projectId === projectId && t.isActive);
  }
  const rows = await listAllPages(SETS.tasks, `statecode eq 0 and _ever_project_value eq ${projectId}`, "ever_name asc");
  return rows.map(mapTask);
}

export async function getAllTasks(): Promise<Task[]> {
  if (!isPowerAppsHost()) {
    return load<Task>(STORAGE_KEYS.tasks).filter((t) => t.isActive);
  }
  const rows = await listAllPages(SETS.tasks, "statecode eq 0", "ever_name asc");
  return rows.map(mapTask);
}

export async function createTask(data: Omit<Task, "id">): Promise<Task> {
  if (!isPowerAppsHost()) {
    const task: Task = { ...data, id: uuid() };
    const all = load<Task>(STORAGE_KEYS.tasks);
    persist(STORAGE_KEYS.tasks, [...all, task]);
    return task;
  }
  const result = await retryWithBackoff(() => MicrosoftDataverseService.CreateRecordWithOrganization(
    PREFER_RETURN,
    ACCEPT,
    orgUrl(),
    SETS.tasks,
    taskToDataverse(data),
  ));
  const inputAsTask: Task = { ...data, id: "" };
  return mergeOver(inputAsTask, mapTask(unwrapRow(unwrap(result, "Create task"))));
}

// Shared by every entity's delete: local-mock filter/persist, or a Dataverse
// delete that treats a 404 as success (a retried attempt can legitimately hit
// one if an earlier try already succeeded server-side but its response was
// lost — the caller's goal, the record no longer existing, is already met).
async function deleteRecord<T extends { id: string }>(
  storageKey: string, setName: string, id: string, label: string
): Promise<void> {
  if (!isPowerAppsHost()) {
    const all = load<T>(storageKey).filter((r) => r.id !== id);
    persist(storageKey, all);
    return;
  }
  try {
    const result = await retryWithBackoff(() =>
      MicrosoftDataverseService.DeleteRecordWithOrganization(orgUrl(), setName, id)
    );
    unwrap(result, label);
  } catch (err) {
    if (isNotFoundError(err)) return;
    throw err;
  }
}

export async function deleteTask(id: string): Promise<void> {
  return deleteRecord<Task>(STORAGE_KEYS.tasks, SETS.tasks, id, "Delete task");
}

// ---------------------------------------------------------------------------
// Time Entries — scoped to the current user
// ---------------------------------------------------------------------------
// Build a YYYY-MM-DD string from a Date without timezone conversion.
function fmtDate(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

// Minimal escaping for values interpolated into FetchXML condition attributes.
function escapeXmlAttr(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export async function getTimeEntries(opts: { from?: string; to?: string } = {}): Promise<TimeEntry[]> {
  const user = getCurrentUser();
  // Always apply a date range — default to the last 30 days to avoid
  // unbounded fetches for large orgs.
  const today = new Date();
  const thirtyDaysAgo = new Date(today);
  thirtyDaysAgo.setDate(today.getDate() - 29);
  const from = opts.from ?? fmtDate(thirtyDaysAgo);
  const to = opts.to ?? fmtDate(today);

  if (!isPowerAppsHost()) {
    return load<TimeEntry>(STORAGE_KEYS.entries)
      .filter((e) => e.userId === user.id && e.date >= from && e.date <= to)
      .sort((a, b) => b.startTime.localeCompare(a.startTime));
  }
  // Filters server-side via FetchXML's eq-userid operator, which Dataverse
  // resolves to "the calling user" itself. This is a genuine data-level
  // filter — unlike the ever_userid column filter removed here previously
  // (which broke on objectId drift across SDK sessions), eq-userid doesn't
  // depend on comparing stored ids from this layer, and it holds even if
  // the ever_timeentries security role's row-scope is misconfigured (see
  // README "Row security matters" / hasForeignUserEntries below).
  const fetchXml =
    '<fetch>' +
      '<entity name="ever_timeentries">' +
        '<all-attributes />' +
        '<filter>' +
          `<condition attribute="ever_date" operator="ge" value="${escapeXmlAttr(from)}" />` +
          `<condition attribute="ever_date" operator="le" value="${escapeXmlAttr(to)}" />` +
          '<condition attribute="ownerid" operator="eq-userid" />' +
        '</filter>' +
        '<order attribute="ever_starttime" descending="true" />' +
      '</entity>' +
    '</fetch>';
  const rows = await listAllPages(SETS.entries, undefined, undefined, fetchXml);
  return rows.map((r) => {
    const entry = mapEntry(r);
    if (!entry.userDisplayName) entry.userDisplayName = user.displayName;
    return entry;
  });
}

/**
 * True if any entry in a getTimeEntries() result belongs to someone other
 * than currentUserId. getTimeEntries() filters server-side by eq-userid, so
 * this should never trip — it's a defense-in-depth / UAT sign-off check. If
 * this ever returns true, something is seriously wrong (e.g. a stale
 * FetchXML condition, or a Dataverse version that doesn't honor eq-userid
 * the way this app expects) and other users' time entries are leaking to
 * the client.
 *
 * Caveat: this compares the stored ever_userid against the current
 * getCurrentUser().id, both ultimately sourced from the SDK's
 * getContext().user.objectId. If that id were ever to drift for the same
 * person across sessions, older rows of theirs would look "foreign" here
 * even though no other user can see them — a false positive, not a leak.
 */
export function hasForeignUserEntries(entries: TimeEntry[], currentUserId: string): boolean {
  return entries.some((e) => e.userId && e.userId !== currentUserId);
}

export async function createTimeEntry(data: Omit<TimeEntry, "id">): Promise<TimeEntry> {
  const user = getCurrentUser();
  const owned = { ...data, userId: user.id, userDisplayName: user.displayName };
  if (!isPowerAppsHost()) {
    const entry: TimeEntry = { ...owned, id: uuid() };
    const all = load<TimeEntry>(STORAGE_KEYS.entries);
    persist(STORAGE_KEYS.entries, [...all, entry]);
    return entry;
  }
  const result = await retryWithBackoff(() => MicrosoftDataverseService.CreateRecordWithOrganization(
    PREFER_RETURN,
    ACCEPT,
    orgUrl(),
    SETS.entries,
    entryToDataverse(owned),
  ));
  const inputAsEntry: TimeEntry = { ...owned, id: "" };
  const merged = mergeOver(inputAsEntry, mapEntry(unwrapRow(unwrap(result, "Create entry"))));
  if (!merged.userDisplayName) merged.userDisplayName = user.displayName;
  return merged;
}

export async function updateTimeEntry(id: string, data: Partial<TimeEntry>): Promise<TimeEntry> {
  const user = getCurrentUser();
  const owned = { ...data, userId: user.id, userDisplayName: user.displayName };
  if (!isPowerAppsHost()) {
    const all = load<TimeEntry>(STORAGE_KEYS.entries);
    const idx = all.findIndex((e) => e.id === id);
    if (idx === -1) throw new Error("Entry not found");
    all[idx] = { ...all[idx], ...owned };
    persist(STORAGE_KEYS.entries, all);
    return all[idx];
  }
  const result = await retryWithBackoff(() => MicrosoftDataverseService.UpdateRecordWithOrganization(
    PREFER_RETURN,
    ACCEPT,
    orgUrl(),
    SETS.entries,
    id,
    entryToDataverse(owned),
  ));
  const inputAsEntry = { ...owned, id } as TimeEntry;
  const merged = mergeOver(inputAsEntry, mapEntry(unwrapRow(unwrap(result, "Update entry"))));
  if (!merged.userDisplayName) merged.userDisplayName = user.displayName;
  return merged;
}

/**
 * Creates a draft timer entry in Dataverse when the timer starts (#15).
 * The record has ever_endtime = null so it can be detected on bootstrap.
 */
export async function createDraftTimerEntry(data: {
  projectId: string;
  taskId?: string | null;
  description?: string;
  startTime: string;
  date: string;
  ratio?: number;
}): Promise<string> {
  const user = getCurrentUser();
  if (!isPowerAppsHost()) {
    // In dev, store draft ID in localStorage so we can clean it up on stop.
    const id = uuid();
    const all = load<TimeEntry>(STORAGE_KEYS.entries);
    persist(STORAGE_KEYS.entries, [...all, {
      ...data,
      taskId: data.taskId ?? undefined,
      id,
      endTime: undefined,
      userId: user.id,
      userDisplayName: user.displayName,
    }]);
    return id;
  }
  const raw: Record<string, unknown> = {
    ever_starttime: data.startTime,
    ever_date: data.date,
    ever_userid: user.id,
    ever_endtime: null,
    [`ever_project@odata.bind`]: `/${SETS.projects}(${data.projectId})`,
  };
  if (data.description) raw.ever_description = data.description;
  if (data.ratio !== undefined) raw.ever_ratio = data.ratio;
  if (data.taskId) raw[`ever_workitem@odata.bind`] = `/${SETS.tasks}(${data.taskId})`;
  const result = await retryWithBackoff(() => MicrosoftDataverseService.CreateRecordWithOrganization(
    PREFER_RETURN, ACCEPT, orgUrl(), SETS.entries, raw,
  ));
  const row = unwrapRow(unwrap(result, "Create draft timer entry"));
  return (row["ever_timeentriesid"] ?? row["id"]) as string;
}

/**
 * Queries for an open timer entry (ever_endtime null) owned by the current
 * user. Used on app bootstrap to restore timer state after a page reload (#15).
 *
 * Filters server-side via FetchXML's eq-userid operator, which Dataverse
 * resolves to "the calling user" itself — this sidesteps the objectId-drift
 * problem that motivated removing the ever_userid filter from getTimeEntries()
 * (see README "Row security matters") while still preventing a user with
 * broader read privileges (admins, BU-level managers) from restoring someone
 * else's in-progress timer into their own timer bar.
 */
export async function getOpenTimerEntry(): Promise<TimeEntry | null> {
  if (!isPowerAppsHost()) {
    const user = getCurrentUser();
    const all = load<TimeEntry>(STORAGE_KEYS.entries);
    const open = all.find((e) => e.userId === user.id && !e.endTime);
    return open ?? null;
  }
  const fetchXml =
    '<fetch top="1">' +
      '<entity name="ever_timeentries">' +
        '<all-attributes />' +
        '<filter>' +
          '<condition attribute="ever_endtime" operator="null" />' +
          '<condition attribute="ownerid" operator="eq-userid" />' +
        '</filter>' +
        '<order attribute="ever_starttime" descending="true" />' +
      '</entity>' +
    '</fetch>';
  try {
    const result = await MicrosoftDataverseService.ListRecordsWithOrganization(
      orgUrl(),
      SETS.entries,
      undefined, // prefer
      ACCEPT,
      undefined, // x-ms-odata-metadata-full
      undefined, // MSCRM.IncludeMipSensitivityLabel
      undefined, // $select
      undefined, // $filter
      undefined, // $orderby
      undefined, // $expand
      fetchXml,
      undefined, // $top
      undefined, // $skiptoken
    );
    const env = unwrap(result, "Get open timer entry") as unknown as ListEnvelope;
    const rows = (env?.value ?? []).map(unwrapRow);
    if (!rows.length) return null;
    // No client-side ownership re-check here: eq-userid above is resolved
    // by Dataverse against the calling user's actual token, so — unlike a
    // compare against the stored ever_userid column — it isn't subject to
    // that column's known objectId drift across SDK sessions (see README
    // "Row security matters"). Re-checking with the drift-prone column here
    // would risk rejecting the user's own timer, not add real protection.
    return mapEntry(rows[0]);
  } catch {
    // If the query fails (e.g. column not filterable), fail gracefully.
    return null;
  }
}

function isNotFoundError(err: unknown): boolean {
  if (!err || typeof err !== "object") return false;
  const e = err as Record<string, unknown>;
  const status = typeof e.status === "number" ? e.status
    : typeof e.statusCode === "number" ? e.statusCode
    : 0;
  if (status === 404) return true;
  const msg = typeof e.message === "string" ? e.message : "";
  return msg.includes("404");
}

export async function deleteTimeEntry(id: string): Promise<void> {
  return deleteRecord<TimeEntry>(STORAGE_KEYS.entries, SETS.entries, id, "Delete entry");
}

// ---------------------------------------------------------------------------
// Bulk writes (issue #8) — creates run in parallel via individual creates,
// faster than serial requests even without a single-round-trip guarantee.
// ---------------------------------------------------------------------------

export type BatchCreateOutcome =
  | { status: "fulfilled"; item: Omit<TimeEntry, "id">; entry: TimeEntry }
  | { status: "rejected"; item: Omit<TimeEntry, "id">; error: unknown };

/**
 * Bulk-creates time entries via parallel individual creates. Uses
 * Promise.allSettled (not Promise.all) so one failed item doesn't hide which
 * of the others already succeeded — callers can inspect each outcome and
 * retry only the rejected items instead of resubmitting the whole batch.
 */
export async function batchCreateTimeEntries(
  items: Omit<TimeEntry, "id">[],
): Promise<BatchCreateOutcome[]> {
  if (!isPowerAppsHost() || items.length === 0) {
    // Dev mock: insert all at once.
    const user = getCurrentUser();
    const created: TimeEntry[] = items.map((data) => ({
      ...data,
      id: uuid(),
      userId: user.id,
      userDisplayName: user.displayName,
    }));
    const all = load<TimeEntry>(STORAGE_KEYS.entries);
    persist(STORAGE_KEYS.entries, [...all, ...created]);
    return created.map((entry, i) => ({ status: "fulfilled", item: items[i], entry }));
  }

  const settled = await Promise.allSettled(items.map((data) => createTimeEntry(data)));
  return settled.map((result, i) =>
    result.status === "fulfilled"
      ? { status: "fulfilled", item: items[i], entry: result.value }
      : { status: "rejected", item: items[i], error: result.reason }
  );
}
