/**
 * dataverseService.ts
 *
 * Talks to Microsoft Dataverse via the @microsoft/power-apps SDK using the
 * code generated by `pac code add-data-source` into src/generated/. When the
 * app runs outside the Power Apps host (Vite dev), it falls back to a
 * localStorage-backed mock with identical semantics.
 *
 * Dataverse tables (must exist in the env before deploying; logical names
 * use the singular, entity-set names use the plural -ses form):
 *   ever_projects    / ever_projectses    — Project records
 *   ever_workitems   / ever_workitemses   — Work Item records
 *   ever_timeentries / ever_timeentrieses — Time Entry records
 *
 * Lookup columns are `ever_project` and `ever_workitem` (NOT *_id). On reads
 * they surface as `_ever_project_value` / `_ever_workitem_value`; writes use
 * `ever_project@odata.bind` / `ever_workitem@odata.bind` with the entity-SET
 * path (plural form), e.g. `/ever_projectses(<guid>)`.
 *
 * Time entries are user-scoped: reads filter by ever_userid eq <current user>,
 * writes stamp the current user. Make sure initCurrentUser() has resolved
 * before calling any of these.
 */
import type { Project, Task, TimeEntry } from "../types";
import { getCurrentUser, isPowerAppsHost } from "./userService";
import { MicrosoftDataverseService } from "../generated";

// ---------------------------------------------------------------------------
// Entity logical names (FetchXML, $filter on lookups) vs entity SET names
// (Web API paths and @odata.bind). The Dataverse pluralization rule appends
// "es" to names already ending in "s", so all three of ours look like ...ses.
// ---------------------------------------------------------------------------
const SETS = {
  projects: "ever_projectses",
  tasks: "ever_workitemses",
  entries: "ever_timeentrieses",
} as const;

const ACCEPT = "application/json";
const PREFER_RETURN = "return=representation";
// PA-Dev org URL. Required by every *WithOrganization SDK call because the
// "current environment" variants (CreateRecord, ListRecords, ...) fail with
// "Invalid organization URL 'null' provided" when the connector can't infer
// the org from the connection. See timeflow-dataverse-schema memory.
const ORG_URL = "https://org010c8ca4.crm.dynamics.com";

function escapeOData(value: string): string {
  return value.replace(/'/g, "''");
}

// ---------------------------------------------------------------------------
// SDK result helpers — every call returns { success, data, error? }; unwrap
// or throw so the calling hooks can keep using try/catch.
// ---------------------------------------------------------------------------
function unwrap<T>(result: { success: boolean; data: T; error?: unknown }, op: string): T {
  if (!result.success) {
    const err = result.error;
    if (err instanceof Error) throw err;
    throw new Error(`${op} failed: ${typeof err === "string" ? err : JSON.stringify(err ?? {})}`);
  }
  return result.data;
}

// The ListRecords response is an OData v9 envelope with a `value` array.
interface ListEnvelope<T> { value: T[]; "@odata.nextLink"?: string }

// ---------------------------------------------------------------------------
// Dataverse <-> model mapping
// ---------------------------------------------------------------------------
type Raw = Record<string, unknown>;

function str(r: Raw, key: string): string | undefined {
  const v = r[key];
  return typeof v === "string" ? v : undefined;
}

function num(r: Raw, key: string): number | undefined {
  const v = r[key];
  return typeof v === "number" && Number.isFinite(v) ? v : undefined;
}

function mapProject(r: Raw): Project {
  return {
    id: (str(r, "ever_projectsid") ?? str(r, "id")) as string,
    name: str(r, "ever_name") ?? "",
    color: str(r, "ever_color") ?? "#6366f1",
    description: str(r, "ever_description"),
    ratio: num(r, "ever_ratio"),
    jiraTicket: str(r, "ever_jiraticket"),
    isActive: num(r, "statecode") === 0,
    createdAt: str(r, "createdon") ?? new Date().toISOString(),
  };
}

function mapTask(r: Raw): Task {
  return {
    id: (str(r, "ever_workitemsid") ?? str(r, "id")) as string,
    projectId: str(r, "_ever_project_value") ?? "",
    name: str(r, "ever_name") ?? "",
    description: str(r, "ever_description"),
    isActive: num(r, "statecode") === 0,
  };
}

function mapEntry(r: Raw): TimeEntry {
  return {
    id: (str(r, "ever_timeentriesid") ?? str(r, "id")) as string,
    projectId: str(r, "_ever_project_value") ?? "",
    taskId: str(r, "_ever_workitem_value"),
    description: str(r, "ever_description"),
    startTime: str(r, "ever_starttime") ?? "",
    endTime: str(r, "ever_endtime"),
    durationMinutes: num(r, "ever_durationminutes"),
    ratio: num(r, "ever_ratio"),
    jiraTicket: str(r, "ever_jiraticket"),
    date: str(r, "ever_date") ?? "",
    userId: str(r, "ever_userid") ?? "",
    userDisplayName: str((r.ownerid as Raw) ?? {}, "fullname") ?? str(r, "ownerid_fullname") ?? "",
  };
}

function projectToDataverse(p: Omit<Project, "id" | "createdAt"> | Partial<Project>): Raw {
  const out: Raw = {};
  if (p.name !== undefined) out.ever_name = p.name;
  if (p.color !== undefined) out.ever_color = p.color;
  if (p.description !== undefined) out.ever_description = p.description ?? null;
  if (p.ratio !== undefined) out.ever_ratio = p.ratio ?? null;
  if (p.jiraTicket !== undefined) out.ever_jiraticket = p.jiraTicket || null;
  return out;
}

function taskToDataverse(t: Omit<Task, "id"> | Partial<Task>): Raw {
  const out: Raw = {};
  if (t.name !== undefined) out.ever_name = t.name;
  if (t.description !== undefined) out.ever_description = t.description ?? null;
  if (t.projectId !== undefined) {
    out["ever_project@odata.bind"] = `/${SETS.projects}(${t.projectId})`;
  }
  return out;
}

function entryToDataverse(e: Omit<TimeEntry, "id"> | Partial<TimeEntry>): Raw {
  const out: Raw = {};
  if (e.description !== undefined) out.ever_description = e.description ?? null;
  if (e.startTime !== undefined) out.ever_starttime = e.startTime;
  if (e.endTime !== undefined) out.ever_endtime = e.endTime ?? null;
  if (e.durationMinutes !== undefined) out.ever_durationminutes = e.durationMinutes ?? null;
  if (e.ratio !== undefined) out.ever_ratio = e.ratio ?? null;
  if (e.jiraTicket !== undefined) out.ever_jiraticket = e.jiraTicket || null;
  if (e.date !== undefined) out.ever_date = e.date;
  out.ever_userid = getCurrentUser().id;
  if (e.projectId !== undefined) {
    out["ever_project@odata.bind"] = `/${SETS.projects}(${e.projectId})`;
  }
  if ("taskId" in e) {
    out["ever_workitem@odata.bind"] = e.taskId ? `/${SETS.tasks}(${e.taskId})` : null;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Local mock store (Vite dev only)
// ---------------------------------------------------------------------------
const STORAGE_KEYS = {
  projects: "tt_projects",
  tasks: "tt_tasks",
  entries: "tt_entries",
} as const;

function load<T>(key: string): T[] {
  try {
    return JSON.parse(localStorage.getItem(key) || "[]") as T[];
  } catch {
    return [];
  }
}

function persist<T>(key: string, data: T[]): void {
  localStorage.setItem(key, JSON.stringify(data));
}

function uuid(): string {
  return crypto.randomUUID();
}

// ---------------------------------------------------------------------------
// Projects
// ---------------------------------------------------------------------------
export async function getProjects(): Promise<Project[]> {
  if (!isPowerAppsHost()) {
    return load<Project>(STORAGE_KEYS.projects)
      .filter((p) => p.isActive)
      .sort((a, b) => a.name.localeCompare(b.name));
  }
  const result = await MicrosoftDataverseService.ListRecordsWithOrganization(
    ORG_URL,
    SETS.projects,
    undefined, // prefer
    ACCEPT,
    undefined, // x-ms-odata-metadata-full
    undefined, // MSCRM.IncludeMipSensitivityLabel
    undefined, // $select
    "statecode eq 0",
    "ever_name asc",
  );
  const env = unwrap(result, "List projects") as unknown as ListEnvelope<Raw>;
  return (env?.value ?? []).map(mapProject);
}

export async function createProject(data: Omit<Project, "id" | "createdAt">): Promise<Project> {
  if (!isPowerAppsHost()) {
    const project: Project = { ...data, id: uuid(), createdAt: new Date().toISOString() };
    const all = load<Project>(STORAGE_KEYS.projects);
    persist(STORAGE_KEYS.projects, [...all, project]);
    return project;
  }
  const result = await MicrosoftDataverseService.CreateRecordWithOrganization(
    PREFER_RETURN,
    ACCEPT,
    ORG_URL,
    SETS.projects,
    projectToDataverse(data),
  );
  const created = unwrap(result, "Create project") as unknown as Raw;
  return mapProject(created ?? {});
}

export async function updateProject(id: string, data: Partial<Project>): Promise<Project> {
  if (!isPowerAppsHost()) {
    const all = load<Project>(STORAGE_KEYS.projects);
    const idx = all.findIndex((p) => p.id === id);
    if (idx === -1) throw new Error("Project not found");
    all[idx] = { ...all[idx], ...data };
    persist(STORAGE_KEYS.projects, all);
    return all[idx];
  }
  const result = await MicrosoftDataverseService.UpdateRecordWithOrganization(
    PREFER_RETURN,
    ACCEPT,
    ORG_URL,
    SETS.projects,
    id,
    projectToDataverse(data),
  );
  const updated = unwrap(result, "Update project") as unknown as Raw;
  return mapProject(updated ?? {});
}

// ---------------------------------------------------------------------------
// Tasks
// ---------------------------------------------------------------------------
export async function getTasksForProject(projectId: string): Promise<Task[]> {
  if (!isPowerAppsHost()) {
    return load<Task>(STORAGE_KEYS.tasks).filter((t) => t.projectId === projectId && t.isActive);
  }
  const result = await MicrosoftDataverseService.ListRecordsWithOrganization(
    ORG_URL,
    SETS.tasks,
    undefined,
    ACCEPT,
    undefined,
    undefined,
    undefined,
    `statecode eq 0 and _ever_project_value eq ${projectId}`,
    "ever_name asc",
  );
  const env = unwrap(result, "List tasks") as unknown as ListEnvelope<Raw>;
  return (env?.value ?? []).map(mapTask);
}

export async function getAllTasks(): Promise<Task[]> {
  if (!isPowerAppsHost()) {
    return load<Task>(STORAGE_KEYS.tasks).filter((t) => t.isActive);
  }
  const result = await MicrosoftDataverseService.ListRecordsWithOrganization(
    ORG_URL,
    SETS.tasks,
    undefined,
    ACCEPT,
    undefined,
    undefined,
    undefined,
    "statecode eq 0",
    "ever_name asc",
  );
  const env = unwrap(result, "List tasks") as unknown as ListEnvelope<Raw>;
  return (env?.value ?? []).map(mapTask);
}

export async function createTask(data: Omit<Task, "id">): Promise<Task> {
  if (!isPowerAppsHost()) {
    const task: Task = { ...data, id: uuid() };
    const all = load<Task>(STORAGE_KEYS.tasks);
    persist(STORAGE_KEYS.tasks, [...all, task]);
    return task;
  }
  const result = await MicrosoftDataverseService.CreateRecordWithOrganization(
    PREFER_RETURN,
    ACCEPT,
    ORG_URL,
    SETS.tasks,
    taskToDataverse(data),
  );
  const created = unwrap(result, "Create task") as unknown as Raw;
  return mapTask(created ?? {});
}

// ---------------------------------------------------------------------------
// Time Entries — scoped to the current user
// ---------------------------------------------------------------------------
export async function getTimeEntries(opts: { from?: string; to?: string } = {}): Promise<TimeEntry[]> {
  const user = getCurrentUser();
  if (!isPowerAppsHost()) {
    let entries = load<TimeEntry>(STORAGE_KEYS.entries).filter((e) => e.userId === user.id);
    if (opts.from) entries = entries.filter((e) => e.date >= opts.from!);
    if (opts.to) entries = entries.filter((e) => e.date <= opts.to!);
    return entries.sort((a, b) => b.startTime.localeCompare(a.startTime));
  }
  const filters = [`ever_userid eq '${escapeOData(user.id)}'`];
  if (opts.from) filters.push(`ever_date ge ${opts.from}`);
  if (opts.to) filters.push(`ever_date le ${opts.to}`);
  const result = await MicrosoftDataverseService.ListRecordsWithOrganization(
    ORG_URL,
    SETS.entries,
    undefined,
    ACCEPT,
    undefined,
    undefined,
    undefined,
    filters.join(" and "),
    "ever_starttime desc",
    "ownerid($select=fullname)",
  );
  const env = unwrap(result, "List entries") as unknown as ListEnvelope<Raw>;
  return (env?.value ?? []).map(mapEntry);
}

export async function createTimeEntry(data: Omit<TimeEntry, "id">): Promise<TimeEntry> {
  const user = getCurrentUser();
  const owned = { ...data, userId: user.id, userDisplayName: user.displayName };
  if (!isPowerAppsHost()) {
    const entry: TimeEntry = { ...owned, id: uuid() };
    const all = load<TimeEntry>(STORAGE_KEYS.entries);
    persist(STORAGE_KEYS.entries, [...all, entry]);
    return entry;
  }
  const result = await MicrosoftDataverseService.CreateRecordWithOrganization(
    PREFER_RETURN,
    ACCEPT,
    ORG_URL,
    SETS.entries,
    entryToDataverse(owned),
  );
  const created = unwrap(result, "Create entry") as unknown as Raw;
  const mapped = mapEntry(created ?? {});
  if (!mapped.userDisplayName) mapped.userDisplayName = user.displayName;
  return mapped;
}

export async function updateTimeEntry(id: string, data: Partial<TimeEntry>): Promise<TimeEntry> {
  const user = getCurrentUser();
  const owned = { ...data, userId: user.id, userDisplayName: user.displayName };
  if (!isPowerAppsHost()) {
    const all = load<TimeEntry>(STORAGE_KEYS.entries);
    const idx = all.findIndex((e) => e.id === id);
    if (idx === -1) throw new Error("Entry not found");
    all[idx] = { ...all[idx], ...owned };
    persist(STORAGE_KEYS.entries, all);
    return all[idx];
  }
  const result = await MicrosoftDataverseService.UpdateRecordWithOrganization(
    PREFER_RETURN,
    ACCEPT,
    ORG_URL,
    SETS.entries,
    id,
    entryToDataverse(owned),
  );
  const updated = unwrap(result, "Update entry") as unknown as Raw;
  const mapped = mapEntry(updated ?? {});
  if (!mapped.userDisplayName) mapped.userDisplayName = user.displayName;
  return mapped;
}

export async function deleteTimeEntry(id: string): Promise<void> {
  if (!isPowerAppsHost()) {
    const all = load<TimeEntry>(STORAGE_KEYS.entries).filter((e) => e.id !== id);
    persist(STORAGE_KEYS.entries, all);
    return;
  }
  const result = await MicrosoftDataverseService.DeleteRecordWithOrganization(ORG_URL, SETS.entries, id);
  unwrap(result, "Delete entry");
}
