/**
 * dataverseService.ts
 *
 * Talks to Microsoft Dataverse via the @microsoft/power-apps SDK using the
 * code generated by `pac code add-data-source` into src/generated/. When the
 * app runs outside the Power Apps host (Vite dev), it falls back to a
 * localStorage-backed mock with identical semantics.
 *
 * Dataverse tables (must exist in the env before deploying; logical names
 * use the singular, entity-set names use the plural -ses form):
 *   ever_projects    / ever_projectses    — Project records
 *   ever_workitems   / ever_workitemses   — Work Item records
 *   ever_timeentries / ever_timeentrieses — Time Entry records
 *
 * Lookup columns are `ever_project` and `ever_workitem` (NOT *_id). On reads
 * they surface as `_ever_project_value` / `_ever_workitem_value`; writes use
 * `ever_project@odata.bind` / `ever_workitem@odata.bind` with the entity-SET
 * path (plural form), e.g. `/ever_projectses(<guid>)`.
 *
 * Time entries are user-scoped, but NOT by comparing ever_userid: reads filter
 * server-side with FetchXML's `eq-userid` operator against `ownerid`, which
 * Dataverse resolves to the calling user itself. `ever_userid` is stamped on
 * write for display/audit only — the SDK has returned inconsistent user ids
 * across sessions, so a filter built from a client-held id can't be trusted.
 * This means the isolation depends on `ever_timeentries` being User-owned;
 * see "Row security matters" in README.md. Make sure initCurrentUser() has
 * resolved before calling any of these.
 */
import type { Project, Task, TimeEntry } from "../types";
import { getCurrentUser, isPowerAppsHost, getDataverseOrgUrl } from "./userService";
import { MicrosoftDataverseService } from "../generated";
import { DEFAULT_PROJECT_COLOR } from "../utils/colors";
import { reportTelemetry } from "./telemetry";

// ---------------------------------------------------------------------------
// Entity logical names (FetchXML, $filter on lookups) vs entity SET names
// (Web API paths and @odata.bind). The Dataverse pluralization rule appends
// "es" to names already ending in "s", so all three of ours look like ...ses.
// ---------------------------------------------------------------------------
const SETS = {
  projects: "ever_projectses",
  tasks: "ever_workitemses",
  entries: "ever_timeentrieses",
} as const;

const ACCEPT = "application/json";
const PREFER_RETURN = "return=representation";

// ---------------------------------------------------------------------------
// Query-literal safety
// ---------------------------------------------------------------------------
// Every value this app interpolates into an OData `$filter` is a record id
// compared against a Uniqueidentifier column, and Dataverse wants those
// unquoted — which means there is no quoting to escape into. The only thing
// that keeps `eq ${id}` from being `$filter` tampering is that `id` really is
// a GUID, so check it here rather than trusting each call site's provenance.
// A non-GUID is a bug (or an attempt), not a query: fail loudly instead of
// sending a filter whose shape we no longer control.
const GUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function odataGuid(value: string | null | undefined): string {
  if (typeof value !== "string" || !GUID_RE.test(value)) {
    throw new Error("Invalid record id");
  }
  return value;
}
// Org URL, required by every *WithOrganization SDK call (the connector rejects
// the no-org "current environment" variants with HTTP 400). Resolved at RUNTIME
// from the connection via getDataverseOrgUrl() — see userService — so a single
// promoted build targets dev in dev, QA in QA, and prod in prod automatically.
// (Baking it in at build time broke one-artifact promotion: a promoted build
// kept calling whichever environment it was compiled against.)
function orgUrl(): string {
  return getDataverseOrgUrl();
}

// ---------------------------------------------------------------------------
// Retry helper — wraps reads and writes with exponential backoff for transient
// Dataverse failures.
//
// Transience comes in two flavours, and the difference decides whether a WRITE
// may be replayed (#97):
//
//   "rejected"  — 429 / 503. The service refused the request before acting on
//                 it, so nothing was applied and anything may be replayed.
//   "ambiguous" — a dropped connection (fetch rejects with a TypeError and no
//                 status at all), a 502 / 504 from a gateway, or the browser
//                 reporting itself offline. The request may well have reached
//                 Dataverse and been applied; only the answer was lost.
//
// Replaying an ambiguous failure is safe for reads, and for the updates and
// deletes in this file — a PATCH with If-Match: "*" re-sends the same fields,
// and deleteRecord() already treats a 404 as success for exactly this reason.
// It is NOT safe for a create: a POST that landed and lost its response would
// be written a second time, and a duplicated time entry is a wrong number on
// someone's invoice — worse than the error toast the caller shows today. So the
// create paths pass `idempotent: false` and keep their existing manual retry
// (the timer's pendingStopAt latch; a toast plus a re-submit everywhere else).
//
// Before this split only 429 and 503 counted, which meant the single most
// common real-world failure — a dropped connection, which carries no status —
// was thrown straight through on the first attempt.
// ---------------------------------------------------------------------------
type Transience = "rejected" | "ambiguous" | "fatal";

function classifyError(err: unknown): Transience {
  // A network-level fetch failure is a bare TypeError with no status: the
  // request never completed, but we can't tell how far it got.
  if (err instanceof TypeError) return "ambiguous";
  if (!err || typeof err !== "object") return "fatal";
  const e = err as Record<string, unknown>;
  const status = typeof e.status === "number" ? e.status
    : typeof e.statusCode === "number" ? e.statusCode
    : 0;
  // Some SDK errors carry the status in the message string instead.
  const msg = typeof e.message === "string" ? e.message : "";
  const has = (code: number) => status === code || msg.includes(String(code));

  if (has(429) || has(503)) return "rejected";
  if (has(502) || has(504)) return "ambiguous";
  // Nothing recognizable, but the browser says there's no network — the error
  // is almost certainly the outage rather than anything Dataverse decided.
  if (typeof navigator !== "undefined" && navigator.onLine === false) return "ambiguous";
  return "fatal";
}

interface RetryOptions {
  maxAttempts?: number;
  /** False for creates: an ambiguous failure must not be replayed. */
  idempotent?: boolean;
}

async function retryWithBackoff<T>(fn: () => Promise<T>, opts: RetryOptions = {}): Promise<T> {
  const { maxAttempts = 3, idempotent = true } = opts;
  let delay = 1000;
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      return await fn();
    } catch (err: unknown) {
      const transience = classifyError(err);
      const retryable = transience === "rejected" || (transience === "ambiguous" && idempotent);

      if (!retryable || attempt === maxAttempts) throw err;

      // Respect Retry-After header when available (SDK may surface it as retryAfter).
      const retryAfterSec = (() => {
        const e = err as Record<string, unknown>;
        const v = e.retryAfter ?? e["retry-after"];
        const n = Number(v);
        return Number.isFinite(n) && n > 0 ? n * 1000 : null;
      })();

      await new Promise((res) => setTimeout(res, retryAfterSec ?? delay));
      delay *= 2;
    }
  }
  throw new Error("retryWithBackoff: unreachable");
}

// ---------------------------------------------------------------------------
// Update helper — the connector exposes two update operations and they are NOT
// interchangeable: UpdateRecordWithOrganization is an *upsert* (it creates the
// row when the id doesn't exist), while UpdateOnlyRecordWithOrganization sends
// an If-Match header so a missing row 404s. Every update in this file goes
// through here so a concurrently deleted record can't be silently resurrected
// as a half-populated row — the callers' isNotFoundError() branches all assume
// update-only semantics.
//
// If-Match: "*" means "the row must exist" without pinning a specific version,
// so concurrent edits from two tabs are still last-writer-wins. Threading real
// ETags through would upgrade that to optimistic concurrency; see issue #72.
// ---------------------------------------------------------------------------
const IF_MATCH_ANY = "*";

// unwrap() runs inside the retried callback, as on the read path: the SDK
// reports some failures as a { success: false } envelope rather than a throw,
// and a throttled update returned that way would otherwise skip the backoff.
function updateOnly(
  entitySet: string, id: string, item: Raw, label: string,
): Promise<Record<string, unknown>> {
  return retryWithBackoff(async () => {
    const result = await MicrosoftDataverseService.UpdateOnlyRecordWithOrganization(
      PREFER_RETURN,
      ACCEPT,
      IF_MATCH_ANY,
      orgUrl(),
      entitySet,
      id,
      item,
    );
    return unwrap(result, label);
  });
}

// Mirrors Dataverse's "row doesn't exist" response in the dev mock so callers'
// isNotFoundError() branches take the same path in dev as in the Power Apps host.
function notFoundError(message: string): Error {
  return Object.assign(new Error(message), { status: 404 });
}

// ---------------------------------------------------------------------------
// SDK result helpers — every call returns { success, data, error? }; unwrap
// or throw so the calling hooks can keep using try/catch.
// ---------------------------------------------------------------------------
function unwrap<T>(result: { success: boolean; data: T; error?: unknown }, op: string): T {
  if (!result.success) {
    const err = result.error;
    if (err instanceof Error) throw err;
    throw new Error(`${op} failed: ${typeof err === "string" ? err : JSON.stringify(err ?? {})}`);
  }
  return result.data;
}

// The ListRecords response is an OData v9 envelope with a `value` array.
// Each item is wrapped by the SDK as `{ dynamicProperties: { ...row } }`.
// FetchXML-based queries page differently from $filter ones (see below), so
// the envelope can also carry a paging-cookie annotation instead of nextLink.
interface DynItem { dynamicProperties?: Raw }
interface ListEnvelope {
  value?: DynItem[];
  "@odata.nextLink"?: string;
  "@Microsoft.Dynamics.CRM.fetchxmlpagingcookie"?: string;
}

// Dataverse caps list responses (default 5,000 rows) and signals more data via
// @odata.nextLink. Pull the $skiptoken out of that link so we can keep paging
// through the SDK, which accepts $skiptoken but not a raw nextLink URL.
function extractSkipToken(nextLink?: string): string | undefined {
  if (!nextLink) return undefined;
  try {
    return new URL(nextLink).searchParams.get("$skiptoken") ?? undefined;
  } catch {
    return undefined;
  }
}

// Rows per FetchXML page. Set explicitly (rather than relying on the server
// default) so "a short page is the last page" — the documented termination
// rule — has a known threshold to compare against. 5,000 is Dataverse's
// maximum page size, so this doesn't add round-trips to normal loads.
const FETCH_PAGE_SIZE = 5000;

// FetchXML-based Web API queries don't page via @odata.nextLink/$skiptoken —
// Dataverse instead returns a paging-cookie annotation whose *inner*
// pagingcookie value must be echoed back as a `paging-cookie` attribute on
// <fetch>, alongside an incremented `page` attribute, to get the next page.
function withFetchPaging(fetchXml: string, page: number, pagingCookie?: string): string {
  const cookieAttr = pagingCookie ? ` paging-cookie="${escapeXmlAttr(pagingCookie)}"` : "";
  // Replacer function, not a replacement string: `$&`, "$`", `$'` and `$n` are
  // special on the right-hand side of String.replace, and the cookie is server
  // data that can legitimately contain a `$`. A replacer keeps every character
  // literal.
  return fetchXml.replace(
    /<fetch(\s|>)/,
    (_match, tail: string) => `<fetch count="${FETCH_PAGE_SIZE}" page="${page}"${cookieAttr}${tail}`,
  );
}

// The annotation is itself a scrap of XML wrapping the value we actually need:
//   <cookie pagenumber="1" pagingcookie="%253ccookie%2520pagenumber%253d..." istracking="False" />
// Only the inner `pagingcookie` attribute goes back to Dataverse, and it
// arrives double-URL-encoded. Echoing the whole annotation verbatim (as this
// did before #69) produces a malformed page-2 request, which the mid-pagination
// catch below then turns into silently truncated data.
export function extractPagingCookie(annotation?: string): string | undefined {
  if (!annotation) return undefined;
  const match = /\bpagingcookie\s*=\s*("([^"]*)"|'([^']*)')/.exec(annotation);
  const encoded = match?.[2] ?? match?.[3];
  if (!encoded) return undefined;
  try {
    return decodeURIComponent(decodeURIComponent(decodeXmlAttr(encoded)));
  } catch {
    // Malformed percent-escapes: better to stop paging (and warn) than to
    // send a cookie Dataverse will reject.
    console.error("Could not decode the FetchXML paging cookie.");
    return undefined;
  }
}

// Inverse of escapeXmlAttr, for reading a value back out of an XML attribute.
// &amp; is unescaped last so "&amp;lt;" round-trips to "&lt;", not "<".
function decodeXmlAttr(value: string): string {
  return value
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

// Hard ceiling so a misbehaving nextLink/paging-cookie can never loop forever.
const MAX_PAGES = 20;

// Just the message, for telemetry props — an Error's stack is noise in a
// dashboard and a raw object stringifies to "[object Object]".
function errText(err: unknown): string {
  if (err instanceof Error) return err.message;
  return typeof err === "string" ? err : JSON.stringify(err ?? {});
}

// Module-level warning sink. Wire up via setPaginationWarningHandler() so the
// service can surface non-fatal partial-load warnings to the UI without
// importing React or hooks.
type WarningHandler = (message: string) => void;
let paginationWarningHandler: WarningHandler | null = null;
export function setPaginationWarningHandler(fn: WarningHandler | null): void {
  paginationWarningHandler = fn;
}

async function listAllPages(
  entitySet: string,
  filter: string | undefined,
  orderby: string | undefined,
  fetchXml?: string,
): Promise<Raw[]> {
  const rows: Raw[] = [];
  let skiptoken: string | undefined;
  let pagingCookie: string | undefined;
  // True while a page has been consumed but the server may still hold more.
  // Cleared by whichever branch below decides we've reached the end, so it is
  // still set if the loop falls out of MAX_PAGES with data left behind.
  let morePages = false;
  for (let page = 0; page < MAX_PAGES; page++) {
    morePages = false;
    let env: ListEnvelope;
    try {
      // Reads get the same backoff as writes: a single transient 429/503 on a
      // page would otherwise fail the whole load (blank timesheet + error
      // toast) even though the next attempt would have succeeded. unwrap() is
      // inside the retried callback so a { success: false } envelope carrying
      // a throttling error is retried too, not just a thrown one.
      env = await retryWithBackoff(async () => {
        const result = await MicrosoftDataverseService.ListRecordsWithOrganization(
          orgUrl(),
          entitySet,
          undefined, // prefer
          ACCEPT,
          undefined, // x-ms-odata-metadata-full
          undefined, // MSCRM.IncludeMipSensitivityLabel
          undefined, // $select
          fetchXml ? undefined : filter,
          fetchXml ? undefined : orderby,
          undefined, // $expand
          fetchXml ? withFetchPaging(fetchXml, page + 1, pagingCookie) : undefined,
          undefined, // $top
          fetchXml ? undefined : skiptoken,
        );
        return unwrap(result, `List ${entitySet}`) as unknown as ListEnvelope;
      });
    } catch (err) {
      if (page === 0) {
        // First page failure is fatal — there's nothing useful to return.
        throw err;
      }
      // Mid-pagination error: return what we have and warn the user. Reported
      // too — the user's toast says "some entries may not be shown", which
      // nobody can act on without knowing which table and which page (#111).
      reportTelemetry({
        name: "pagination_truncated",
        severity: "error",
        message: `Pagination failed on page ${page} of ${entitySet}`,
        props: { entitySet, page, rowsSoFar: rows.length, reason: "page_error", error: errText(err) },
      });
      paginationWarningHandler?.(
        "Some entries may not be shown — try narrowing your date range"
      );
      return rows;
    }
    const items = env?.value ?? [];
    for (const item of items) rows.push(unwrapRow(item));
    if (fetchXml) {
      // Termination is "the page came back short", not "the annotation is
      // absent": Dataverse returns the paging cookie on every page that
      // yields rows, including the last one. Keying off its presence made
      // routine loads issue an extra (malformed) request and then warn the
      // user about truncation that never happened (#69).
      if (items.length < FETCH_PAGE_SIZE) break;
      morePages = true;
      pagingCookie = extractPagingCookie(env?.["@Microsoft.Dynamics.CRM.fetchxmlpagingcookie"]);
      // A full page with no usable cookie is ambiguous — either an exactly
      // page-size result set, or an annotation we couldn't parse. We can't
      // ask for page 2 without it, so stop and let the warning below say so
      // rather than quietly dropping whatever follows.
      if (!pagingCookie) break;
    } else {
      skiptoken = extractSkipToken(env?.["@odata.nextLink"]);
      if (!skiptoken) break;
      morePages = true;
    }
  }
  if (morePages) {
    // Exceeded MAX_PAGES — return partial data with a warning rather than
    // throwing, so the user sees what was loaded instead of a blank page.
    reportTelemetry({
      name: "pagination_truncated",
      severity: "error",
      message: `Loading ${entitySet} exceeded ${MAX_PAGES} pages; partial data returned`,
      props: { entitySet, page: MAX_PAGES, rowsSoFar: rows.length, reason: "max_pages" },
    });
    paginationWarningHandler?.(
      "Some entries may not be shown — try narrowing your date range"
    );
  }
  return rows;
}

// The SDK wraps Dataverse rows (both list items and create/update responses)
// in a `dynamicProperties` object. Peel that off so the mappers see the row.
function unwrapRow(x: unknown): Raw {
  if (!x || typeof x !== "object") return {};
  const obj = x as Raw;
  const dyn = obj.dynamicProperties;
  if (dyn && typeof dyn === "object") return dyn as Raw;
  return obj;
}

// Returns true if val looks like a meaningful field value (not "" / null / undefined).
function isFilled(val: unknown): boolean {
  if (val === undefined || val === null) return false;
  if (typeof val === "string") return val.length > 0;
  return true;
}

// Overlay mapped onto input: keep mapped fields where present, otherwise fall
// back to whatever we sent. Covers the case where the Dataverse connector
// silently drops the response body despite prefer=return=representation, which
// would otherwise replace the user's optimistic record with empty fields.
export function mergeOver<T extends object>(input: T, mapped: T): T {
  const out: Record<string, unknown> = { ...(input as Record<string, unknown>) };
  for (const [k, v] of Object.entries(mapped as Record<string, unknown>)) {
    if (isFilled(v)) out[k] = v;
  }
  return out as T;
}

// Every mapped field whose mapper substitutes a *non-empty* default when its
// column is missing, paired with the column it comes from. These are the only
// fields mergeOver can't be trusted with on a possibly-empty row: the default
// passes isFilled(), so it overwrites the optimistic value instead of losing
// to it. An absent `statecode` reports isActive: false and archives a project
// the user just created; an absent `ever_color` repaints it the default
// indigo; an absent `createdon` restamps its creation date as now (#70).
//
// Mappers whose fallbacks are "" or undefined (name, description, every field
// of mapEntry) need no entry here — isFilled() already rejects those.
const DERIVED_FIELDS: { field: string; column: string }[] = [
  { field: "isActive", column: "statecode" },
  { field: "color", column: "ever_color" },
  { field: "createdAt", column: "createdon" },
];

// mergeOver for a create/update response row, which may be empty. Drops the
// derived fields above when the row doesn't actually carry their source
// column, so the caller's own value survives instead of being overwritten by
// a fabricated default.
function mergeResponseRow<T extends object>(input: T, row: Raw, mapped: T): T {
  const known = { ...(mapped as Record<string, unknown>) };
  for (const { field, column } of DERIVED_FIELDS) {
    if (!isFilled(row[column])) delete known[field];
  }
  return mergeOver(input, known as T);
}

// Note the one field mergeOver can't fall back on: the id. There is nothing
// sensible to merge in when the response body is dropped on a create, so these
// functions return id: "" and it is the caller's job to read that as "unknown,
// reconcile on the next refresh" — keeping its optimistic temp id — rather than
// adopting an id that would send later updates and deletes to the collection
// endpoint instead of a row (#70).

// ---------------------------------------------------------------------------
// Dataverse <-> model mapping
// ---------------------------------------------------------------------------
type Raw = Record<string, unknown>;

function str(r: Raw, key: string): string | undefined {
  const v = r[key];
  return typeof v === "string" ? v : undefined;
}

function num(r: Raw, key: string): number | undefined {
  const v = r[key];
  return typeof v === "number" && Number.isFinite(v) ? v : undefined;
}

// Reads always carry `statecode`; a row without it is a dropped/empty response
// body, where "inactive" is a guess — and the damaging one, since an inactive
// project disappears from the pickers. Default to active and let
// mergeResponseRow drop the field entirely on the merge paths.
function mapIsActive(r: Raw): boolean {
  return (num(r, "statecode") ?? 0) === 0;
}

function mapProject(r: Raw): Project {
  return {
    id: (str(r, "ever_projectsid") ?? str(r, "id")) as string,
    name: str(r, "ever_name") ?? "",
    color: str(r, "ever_color") ?? DEFAULT_PROJECT_COLOR,
    description: str(r, "ever_description"),
    ratio: num(r, "ever_ratio"),
    jiraTicket: str(r, "ever_jiraticket"),
    isActive: mapIsActive(r),
    createdAt: str(r, "createdon") ?? new Date().toISOString(),
  };
}

function mapTask(r: Raw): Task {
  return {
    id: (str(r, "ever_workitemsid") ?? str(r, "id")) as string,
    projectId: str(r, "_ever_project_value") ?? "",
    name: str(r, "ever_name") ?? "",
    description: str(r, "ever_description"),
    isActive: mapIsActive(r),
  };
}

export function mapEntry(r: Raw): TimeEntry {
  // Dataverse can return ever_date either as "YYYY-MM-DD" or as a full ISO
  // timestamp ("YYYY-MM-DDT00:00:00Z") depending on the column's behavior.
  // The rest of the app keys calendar/timesheet rows off "YYYY-MM-DD", so
  // anything past the "T" must be stripped.
  const rawDate = str(r, "ever_date") ?? "";
  return {
    id: (str(r, "ever_timeentriesid") ?? str(r, "id")) as string,
    projectId: str(r, "_ever_project_value") ?? "",
    taskId: str(r, "_ever_workitem_value"),
    description: str(r, "ever_description"),
    startTime: str(r, "ever_starttime") ?? "",
    endTime: str(r, "ever_endtime"),
    durationMinutes: num(r, "ever_durationminutes"),
    ratio: num(r, "ever_ratio"),
    jiraTicket: str(r, "ever_jiraticket"),
    date: rawDate.split("T")[0],
    userId: str(r, "ever_userid") ?? "",
    userDisplayName:
      str((r.owninguser as Raw) ?? {}, "fullname") ??
      str((r.ownerid as Raw) ?? {}, "fullname") ??
      str(r, "ownerid_fullname") ??
      "",
  };
}

function projectToDataverse(p: Omit<Project, "id" | "createdAt"> | Partial<Project>): Raw {
  const out: Raw = {};
  if (p.name !== undefined) out.ever_name = p.name;
  if (p.color !== undefined) out.ever_color = p.color;
  if (p.description !== undefined) out.ever_description = p.description ?? null;
  if (p.ratio !== undefined) out.ever_ratio = p.ratio ?? null;
  if (p.jiraTicket !== undefined) out.ever_jiraticket = p.jiraTicket || null;
  return out;
}

function taskToDataverse(t: Omit<Task, "id"> | Partial<Task>): Raw {
  const out: Raw = {};
  if (t.name !== undefined) out.ever_name = t.name;
  if (t.description !== undefined) out.ever_description = t.description ?? null;
  if (t.projectId !== undefined) {
    out["ever_project@odata.bind"] = `/${SETS.projects}(${t.projectId})`;
  }
  return out;
}

export function entryToDataverse(e: Omit<TimeEntry, "id"> | Partial<TimeEntry>): Raw {
  const out: Raw = {};
  if (e.description !== undefined) out.ever_description = e.description ?? null;
  if (e.startTime !== undefined) out.ever_starttime = e.startTime;
  if (e.endTime !== undefined) out.ever_endtime = e.endTime ?? null;
  if (e.durationMinutes !== undefined) out.ever_durationminutes = e.durationMinutes ?? null;
  if (e.ratio !== undefined) out.ever_ratio = e.ratio ?? null;
  // Trimmed here rather than at each caller: the timer bar, the entry modal
  // and "Continue" all feed this, and a whitespace-only ticket should land as
  // null from every one of them.
  if (e.jiraTicket !== undefined) out.ever_jiraticket = e.jiraTicket?.trim() || null;
  if (e.date !== undefined) out.ever_date = e.date;
  out.ever_userid = getCurrentUser().id;
  if (e.projectId !== undefined) {
    out["ever_project@odata.bind"] = `/${SETS.projects}(${e.projectId})`;
  }
  if ("taskId" in e) {
    out["ever_workitem@odata.bind"] = e.taskId ? `/${SETS.tasks}(${e.taskId})` : null;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Local mock store (Vite dev only)
// ---------------------------------------------------------------------------
const STORAGE_KEYS = {
  projects: "tt_projects",
  tasks: "tt_tasks",
  entries: "tt_entries",
} as const;

function load<T>(key: string): T[] {
  try {
    return JSON.parse(localStorage.getItem(key) || "[]") as T[];
  } catch {
    return [];
  }
}

function persist<T>(key: string, data: T[]): void {
  localStorage.setItem(key, JSON.stringify(data));
}

function uuid(): string {
  return crypto.randomUUID();
}

// ---------------------------------------------------------------------------
// Projects
// ---------------------------------------------------------------------------
// Includes archived (inactive) projects so historical entries can always
// resolve their project name and color; pickers filter on isActive.
export async function getProjects(): Promise<Project[]> {
  if (!isPowerAppsHost()) {
    return load<Project>(STORAGE_KEYS.projects)
      .sort((a, b) => a.name.localeCompare(b.name));
  }
  const rows = await listAllPages(SETS.projects, undefined, "ever_name asc");
  return rows.map(mapProject);
}

export async function createProject(data: Omit<Project, "id" | "createdAt">): Promise<Project> {
  if (!isPowerAppsHost()) {
    const project: Project = { ...data, id: uuid(), createdAt: new Date().toISOString() };
    const all = load<Project>(STORAGE_KEYS.projects);
    persist(STORAGE_KEYS.projects, [...all, project]);
    return project;
  }
  const result = await retryWithBackoff(() => MicrosoftDataverseService.CreateRecordWithOrganization(
    PREFER_RETURN,
    ACCEPT,
    orgUrl(),
    SETS.projects,
    projectToDataverse(data),
  ), { idempotent: false }); // POST — see retryWithBackoff's note on ambiguous failures
  // id stays "" when the connector drops the response body — see the note by
  // mergeResponseRow for what callers must do with that.
  const inputAsProject: Project = { ...data, id: "", createdAt: new Date().toISOString() };
  const row = unwrapRow(unwrap(result, "Create project"));
  return mergeResponseRow(inputAsProject, row, mapProject(row));
}

export async function updateProject(id: string, data: Partial<Project>): Promise<Project> {
  if (!isPowerAppsHost()) {
    const all = load<Project>(STORAGE_KEYS.projects);
    const idx = all.findIndex((p) => p.id === id);
    if (idx === -1) throw notFoundError("Project not found");
    all[idx] = { ...all[idx], ...data };
    persist(STORAGE_KEYS.projects, all);
    return all[idx];
  }
  const raw = unwrapRow(await updateOnly(SETS.projects, id, projectToDataverse(data), "Update project"));
  // Patch needs all fields populated for the UI to render correctly even when
  // the connector returns an empty body. Fields the patch didn't touch stay
  // absent from the result, so callers must merge it over the record they
  // already hold rather than replacing that record wholesale.
  const inputAsProject = { ...data, id } as Project;
  return mergeResponseRow(inputAsProject, raw, mapProject(raw));
}

// ---------------------------------------------------------------------------
// Tasks
// ---------------------------------------------------------------------------
// Task reads include inactive (soft-deleted) tasks so historical time entries
// can still resolve their task names in the timesheet, reports and CSV export.
// Pickers filter on isActive client-side.
export async function getTasksForProject(projectId: string): Promise<Task[]> {
  if (!isPowerAppsHost()) {
    return load<Task>(STORAGE_KEYS.tasks).filter((t) => t.projectId === projectId);
  }
  const rows = await listAllPages(SETS.tasks, `_ever_project_value eq ${odataGuid(projectId)}`, "ever_name asc");
  return rows.map(mapTask);
}

export async function getAllTasks(): Promise<Task[]> {
  if (!isPowerAppsHost()) {
    return load<Task>(STORAGE_KEYS.tasks);
  }
  const rows = await listAllPages(SETS.tasks, undefined, "ever_name asc");
  return rows.map(mapTask);
}

export async function createTask(data: Omit<Task, "id">): Promise<Task> {
  if (!isPowerAppsHost()) {
    const task: Task = { ...data, id: uuid() };
    const all = load<Task>(STORAGE_KEYS.tasks);
    persist(STORAGE_KEYS.tasks, [...all, task]);
    return task;
  }
  const result = await retryWithBackoff(() => MicrosoftDataverseService.CreateRecordWithOrganization(
    PREFER_RETURN,
    ACCEPT,
    orgUrl(),
    SETS.tasks,
    taskToDataverse(data),
  ), { idempotent: false });
  const inputAsTask: Task = { ...data, id: "" };
  const row = unwrapRow(unwrap(result, "Create task"));
  return mergeResponseRow(inputAsTask, row, mapTask(row));
}

// Shared by every entity's delete: local-mock filter/persist, or a Dataverse
// delete that treats a 404 as success (a retried attempt can legitimately hit
// one if an earlier try already succeeded server-side but its response was
// lost — the caller's goal, the record no longer existing, is already met).
async function deleteRecord<T extends { id: string }>(
  storageKey: string, setName: string, id: string, label: string
): Promise<void> {
  if (!isPowerAppsHost()) {
    const all = load<T>(storageKey).filter((r) => r.id !== id);
    persist(storageKey, all);
    return;
  }
  try {
    const result = await retryWithBackoff(() =>
      MicrosoftDataverseService.DeleteRecordWithOrganization(orgUrl(), setName, id)
    );
    unwrap(result, label);
  } catch (err) {
    if (isNotFoundError(err)) return;
    throw err;
  }
}

// Tasks and projects are deactivated (statecode 1) rather than hard-deleted:
// a hard delete nulls the lookup on every historical time entry (default
// referential remove-link behavior), silently stripping attribution from past
// reports and exports. Deactivating removes the record from pickers while
// preserving history — and lets undo restore the exact same record instead of
// creating a duplicate with a new id.
async function setRecordState(
  storageKey: string, setName: string, label: string, id: string, active: boolean
): Promise<void> {
  if (!isPowerAppsHost()) {
    const all = load<{ id: string; isActive: boolean }>(storageKey);
    const idx = all.findIndex((r) => r.id === id);
    // Mirror Dataverse's update-only 404 so the tolerate-missing-on-deactivate
    // branch below is exercised in dev too.
    if (idx === -1) {
      if (!active) return;
      throw notFoundError(`${label}: record not found`);
    }
    all[idx] = { ...all[idx], isActive: active };
    persist(storageKey, all);
    return;
  }
  try {
    await updateOnly(setName, id, { statecode: active ? 0 : 1 }, label);
  } catch (err) {
    // Deactivating a record that no longer exists: the goal state is met.
    if (!active && isNotFoundError(err)) return;
    throw err;
  }
}

export async function deactivateTask(id: string): Promise<void> {
  return setRecordState(STORAGE_KEYS.tasks, SETS.tasks, "Deactivate task", id, false);
}

export async function reactivateTask(id: string): Promise<void> {
  return setRecordState(STORAGE_KEYS.tasks, SETS.tasks, "Reactivate task", id, true);
}

export async function deactivateProject(id: string): Promise<void> {
  return setRecordState(STORAGE_KEYS.projects, SETS.projects, "Archive project", id, false);
}

export async function reactivateProject(id: string): Promise<void> {
  return setRecordState(STORAGE_KEYS.projects, SETS.projects, "Restore project", id, true);
}

export async function updateTask(id: string, data: Partial<Task>): Promise<Task> {
  if (!isPowerAppsHost()) {
    const all = load<Task>(STORAGE_KEYS.tasks);
    const idx = all.findIndex((t) => t.id === id);
    if (idx === -1) throw notFoundError("Task not found");
    all[idx] = { ...all[idx], ...data };
    persist(STORAGE_KEYS.tasks, all);
    return all[idx];
  }
  const raw = unwrapRow(await updateOnly(SETS.tasks, id, taskToDataverse(data), "Update task"));
  const inputAsTask = { ...data, id } as Task;
  return mergeResponseRow(inputAsTask, raw, mapTask(raw));
}

// ---------------------------------------------------------------------------
// Time Entries — scoped to the current user
// ---------------------------------------------------------------------------
// Build a YYYY-MM-DD string from a Date without timezone conversion.
function fmtDate(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

// Minimal escaping for values interpolated into FetchXML condition attributes.
// Exported for tests: it's the only thing standing between a caller-supplied
// date string and the FetchXML the server executes.
//
// Both quote characters are escaped, so the result is safe in a single- or
// double-quoted attribute. Callers here always use double quotes, but an
// escaper that is only conditionally correct is one refactor away from being
// incorrect.
export function escapeXmlAttr(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export async function getTimeEntries(opts: { from?: string; to?: string } = {}): Promise<TimeEntry[]> {
  const user = getCurrentUser();
  // Always apply a date range — default to the last 30 days to avoid
  // unbounded fetches for large orgs.
  const today = new Date();
  const thirtyDaysAgo = new Date(today);
  thirtyDaysAgo.setDate(today.getDate() - 29);
  const from = opts.from ?? fmtDate(thirtyDaysAgo);
  const to = opts.to ?? fmtDate(today);

  if (!isPowerAppsHost()) {
    return load<TimeEntry>(STORAGE_KEYS.entries)
      .filter((e) => e.userId === user.id && e.date >= from && e.date <= to)
      .sort((a, b) => b.startTime.localeCompare(a.startTime));
  }
  // Filters server-side via FetchXML's eq-userid operator, which Dataverse
  // resolves to "the calling user" itself. This is a genuine data-level
  // filter — unlike the ever_userid column filter removed here previously
  // (which broke on objectId drift across SDK sessions), eq-userid doesn't
  // depend on comparing stored ids from this layer, and it holds even if
  // the ever_timeentries security role's row-scope is misconfigured (see
  // README "Row security matters" / hasForeignUserEntries below).
  const fetchXml =
    '<fetch>' +
      '<entity name="ever_timeentries">' +
        '<all-attributes />' +
        '<filter>' +
          `<condition attribute="ever_date" operator="ge" value="${escapeXmlAttr(from)}" />` +
          `<condition attribute="ever_date" operator="le" value="${escapeXmlAttr(to)}" />` +
          '<condition attribute="ownerid" operator="eq-userid" />' +
        '</filter>' +
        '<order attribute="ever_starttime" descending="true" />' +
      '</entity>' +
    '</fetch>';
  const rows = await listAllPages(SETS.entries, undefined, undefined, fetchXml);
  return rows.map((r) => {
    const entry = mapEntry(r);
    if (!entry.userDisplayName) entry.userDisplayName = user.displayName;
    return entry;
  });
}

/**
 * True if any entry in a getTimeEntries() result belongs to someone other
 * than currentUserId. getTimeEntries() filters server-side by eq-userid, so
 * this should never trip — it's a defense-in-depth / UAT sign-off check. If
 * this ever returns true, something is seriously wrong (e.g. a stale
 * FetchXML condition, or a Dataverse version that doesn't honor eq-userid
 * the way this app expects) and other users' time entries are leaking to
 * the client.
 *
 * Caveat: this compares the stored ever_userid against the current
 * getCurrentUser().id, both ultimately sourced from the SDK's
 * getContext().user.objectId. If that id were ever to drift for the same
 * person across sessions, older rows of theirs would look "foreign" here
 * even though no other user can see them — a false positive, not a leak.
 */
export function hasForeignUserEntries(entries: TimeEntry[], currentUserId: string): boolean {
  return entries.some((e) => e.userId && e.userId !== currentUserId);
}

export async function createTimeEntry(data: Omit<TimeEntry, "id">): Promise<TimeEntry> {
  const user = getCurrentUser();
  const owned = { ...data, userId: user.id, userDisplayName: user.displayName };
  if (!isPowerAppsHost()) {
    const entry: TimeEntry = { ...owned, id: uuid() };
    const all = load<TimeEntry>(STORAGE_KEYS.entries);
    persist(STORAGE_KEYS.entries, [...all, entry]);
    return entry;
  }
  const result = await retryWithBackoff(() => MicrosoftDataverseService.CreateRecordWithOrganization(
    PREFER_RETURN,
    ACCEPT,
    orgUrl(),
    SETS.entries,
    entryToDataverse(owned),
  ), { idempotent: false }); // a replayed create is a duplicated billable entry
  const inputAsEntry: TimeEntry = { ...owned, id: "" };
  const merged = mergeOver(inputAsEntry, mapEntry(unwrapRow(unwrap(result, "Create entry"))));
  if (!merged.userDisplayName) merged.userDisplayName = user.displayName;
  return merged;
}

export async function updateTimeEntry(id: string, data: Partial<TimeEntry>): Promise<TimeEntry> {
  const user = getCurrentUser();
  const owned = { ...data, userId: user.id, userDisplayName: user.displayName };
  if (!isPowerAppsHost()) {
    const all = load<TimeEntry>(STORAGE_KEYS.entries);
    const idx = all.findIndex((e) => e.id === id);
    // Match Dataverse's update-only semantics so callers' isNotFoundError
    // checks (e.g. useTimer's stop fallback) work in dev.
    if (idx === -1) throw notFoundError("Entry not found");
    all[idx] = { ...all[idx], ...owned };
    persist(STORAGE_KEYS.entries, all);
    return all[idx];
  }
  const row = await updateOnly(SETS.entries, id, entryToDataverse(owned), "Update entry");
  const inputAsEntry = { ...owned, id } as TimeEntry;
  const merged = mergeOver(inputAsEntry, mapEntry(unwrapRow(row)));
  if (!merged.userDisplayName) merged.userDisplayName = user.displayName;
  return merged;
}

// Two timestamps naming the same moment, allowing for the sub-second precision
// Dataverse drops on the round trip. Deliberately tight: anything looser risks
// matching a *different* session's draft, which is worse than not matching at
// all. Unparseable input is not a match.
function sameInstant(a: string | undefined, b: string | undefined): boolean {
  if (!a || !b) return false;
  const ta = new Date(a).getTime();
  const tb = new Date(b).getTime();
  if (!Number.isFinite(ta) || !Number.isFinite(tb)) return false;
  return Math.abs(ta - tb) < 1000;
}

/**
 * Creates a draft timer entry in Dataverse when the timer starts (#15).
 * The record has ever_endtime = null so it can be detected on bootstrap.
 *
 * Returns null when the id can't be established — the row may well exist
 * server-side, we just can't address it. Callers must not store null as the
 * draft id: stopping against one would PATCH `undefined` and leave the real
 * row open, to be restored as a phantom running timer on the next load (#70).
 */
export async function createDraftTimerEntry(data: {
  projectId: string;
  taskId?: string | null;
  description?: string;
  startTime: string;
  date: string;
  ratio?: number;
  jiraTicket?: string;
}): Promise<string | null> {
  const user = getCurrentUser();
  if (!isPowerAppsHost()) {
    // In dev, store draft ID in localStorage so we can clean it up on stop.
    const id = uuid();
    const all = load<TimeEntry>(STORAGE_KEYS.entries);
    persist(STORAGE_KEYS.entries, [...all, {
      ...data,
      taskId: data.taskId ?? undefined,
      id,
      endTime: undefined,
      userId: user.id,
      userDisplayName: user.displayName,
    }]);
    return id;
  }
  const raw: Record<string, unknown> = {
    ever_starttime: data.startTime,
    ever_date: data.date,
    ever_userid: user.id,
    ever_endtime: null,
    [`ever_project@odata.bind`]: `/${SETS.projects}(${data.projectId})`,
  };
  if (data.description) raw.ever_description = data.description;
  if (data.ratio !== undefined) raw.ever_ratio = data.ratio;
  if (data.jiraTicket) raw.ever_jiraticket = data.jiraTicket;
  if (data.taskId) raw[`ever_workitem@odata.bind`] = `/${SETS.tasks}(${data.taskId})`;
  const result = await retryWithBackoff(() => MicrosoftDataverseService.CreateRecordWithOrganization(
    PREFER_RETURN, ACCEPT, orgUrl(), SETS.entries, raw,
  ), { idempotent: false });
  const row = unwrapRow(unwrap(result, "Create draft timer entry"));
  const id = str(row, "ever_timeentriesid") ?? str(row, "id");
  if (id) return id;

  // The connector dropped the response body. The draft is the current user's
  // only open (endTime null) row, so read it back instead of returning an
  // unusable id. The start time must still match — a pre-existing draft from
  // an older session would otherwise be adopted as this one and stopped in
  // its place — but compared as instants, not strings: we send
  // toISOString() with milliseconds and Dataverse hands the column back at
  // second precision, so string equality would reject the very row we just
  // wrote and make this whole fallback dead code.
  try {
    const open = await getOpenTimerEntry();
    if (open?.id && sameInstant(open.startTime, data.startTime)) return open.id;
  } catch {
    // Fall through: "couldn't look it up" and "isn't there" both mean the id
    // is unknown, which is what null says.
  }
  console.warn("Draft timer entry created but its id could not be resolved.");
  return null;
}

/**
 * Queries for an open timer entry (ever_endtime null) owned by the current
 * user. Used on app bootstrap to restore timer state after a page reload (#15).
 *
 * Filters server-side via FetchXML's eq-userid operator, which Dataverse
 * resolves to "the calling user" itself — this sidesteps the objectId-drift
 * problem that motivated removing the ever_userid filter from getTimeEntries()
 * (see README "Row security matters") while still preventing a user with
 * broader read privileges (admins, BU-level managers) from restoring someone
 * else's in-progress timer into their own timer bar.
 */
export async function getOpenTimerEntry(): Promise<TimeEntry | null> {
  if (!isPowerAppsHost()) {
    const user = getCurrentUser();
    const all = load<TimeEntry>(STORAGE_KEYS.entries);
    const open = all.find((e) => e.userId === user.id && !e.endTime);
    return open ?? null;
  }
  const fetchXml =
    '<fetch top="1">' +
      '<entity name="ever_timeentries">' +
        '<all-attributes />' +
        '<filter>' +
          '<condition attribute="ever_endtime" operator="null" />' +
          '<condition attribute="ownerid" operator="eq-userid" />' +
        '</filter>' +
        '<order attribute="ever_starttime" descending="true" />' +
      '</entity>' +
    '</fetch>';
  // Retried and allowed to throw on failure: "there is no open draft" and "we
  // couldn't find out" are different answers, and collapsing them to null lost
  // running timers on a transient 429 during bootstrap — the user would start a
  // second timer and the orphaned draft resurfaced later as a phantom. Callers
  // must treat a rejection as "unknown" and keep local timer state authoritative.
  const env = await retryWithBackoff(async () => {
    const result = await MicrosoftDataverseService.ListRecordsWithOrganization(
      orgUrl(),
      SETS.entries,
      undefined, // prefer
      ACCEPT,
      undefined, // x-ms-odata-metadata-full
      undefined, // MSCRM.IncludeMipSensitivityLabel
      undefined, // $select
      undefined, // $filter
      undefined, // $orderby
      undefined, // $expand
      fetchXml,
      undefined, // $top
      undefined, // $skiptoken
    );
    return unwrap(result, "Get open timer entry") as unknown as ListEnvelope;
  });
  const rows = (env?.value ?? []).map(unwrapRow);
  if (!rows.length) return null;
  // No client-side ownership re-check here: eq-userid above is resolved
  // by Dataverse against the calling user's actual token, so — unlike a
  // compare against the stored ever_userid column — it isn't subject to
  // that column's known objectId drift across SDK sessions (see README
  // "Row security matters"). Re-checking with the drift-prone column here
  // would risk rejecting the user's own timer, not add real protection.
  return mapEntry(rows[0]);
}

export function isNotFoundError(err: unknown): boolean {
  if (!err || typeof err !== "object") return false;
  const e = err as Record<string, unknown>;
  const status = typeof e.status === "number" ? e.status
    : typeof e.statusCode === "number" ? e.statusCode
    : 0;
  if (status === 404) return true;
  const msg = typeof e.message === "string" ? e.message : "";
  return msg.includes("404");
}

export async function deleteTimeEntry(id: string): Promise<void> {
  return deleteRecord<TimeEntry>(STORAGE_KEYS.entries, SETS.entries, id, "Delete entry");
}

// ---------------------------------------------------------------------------
// Bulk writes (issue #8) — creates run in parallel via individual creates,
// faster than serial requests even without a single-round-trip guarantee.
// ---------------------------------------------------------------------------

export type BatchCreateOutcome =
  | { status: "fulfilled"; item: Omit<TimeEntry, "id">; entry: TimeEntry }
  | { status: "rejected"; item: Omit<TimeEntry, "id">; error: unknown };

/**
 * Bulk-creates time entries via parallel individual creates. Uses
 * Promise.allSettled (not Promise.all) so one failed item doesn't hide which
 * of the others already succeeded — callers can inspect each outcome and
 * retry only the rejected items instead of resubmitting the whole batch.
 */
export async function batchCreateTimeEntries(
  items: Omit<TimeEntry, "id">[],
): Promise<BatchCreateOutcome[]> {
  if (!isPowerAppsHost() || items.length === 0) {
    // Dev mock: insert all at once.
    const user = getCurrentUser();
    const created: TimeEntry[] = items.map((data) => ({
      ...data,
      id: uuid(),
      userId: user.id,
      userDisplayName: user.displayName,
    }));
    const all = load<TimeEntry>(STORAGE_KEYS.entries);
    persist(STORAGE_KEYS.entries, [...all, ...created]);
    return created.map((entry, i) => ({ status: "fulfilled", item: items[i], entry }));
  }

  const settled = await Promise.allSettled(items.map((data) => createTimeEntry(data)));
  return settled.map((result, i) =>
    result.status === "fulfilled"
      ? { status: "fulfilled", item: items[i], entry: result.value }
      : { status: "rejected", item: items[i], error: result.reason }
  );
}
